// GENERATED by app/test/record.mjs: analyze() on the recorded ClashDesk survey (test/fixtures/raw.planted.clashdesk.json).
// Do not edit by hand; re-run `node test/record.mjs --offline` (in app/) after any change to src/analyze.js.
// default / report: the CropReport, served by /api/fields as `featured` (source: 'fixture') until the store holds a live PLANTED report.
// The site generates site/src/data from these exports (featured.json = report, idclock.json = idclock).
export const report = {
 "v": 1,
 "checkedAt": "2026-09-25T12:55:00Z",
 "source": "fixture",
 "partial": false,
 "input": {
  "q": "AutocratGirder/ClashDesk",
  "kind": "slug",
  "mint": null,
  "token": null,
  "note": null
 },
 "repo": {
  "fullName": "AutocratGirder/ClashDesk",
  "url": "https://github.com/AutocratGirder/ClashDesk",
  "description": "Modern cross-platform desktop client for proxy workflows",
  "createdAt": "2026-09-23T11:21:44Z",
  "pushedAt": "2026-09-23T11:22:01Z",
  "stars": 224,
  "forks": 47,
  "sizeKb": 4,
  "commits": 4,
  "language": "Rust",
  "owner": {
   "login": "AutocratGirder",
   "id": 307795303,
   "createdAt": "2026-07-21T23:59:38Z",
   "followers": 0,
   "publicRepos": 14
  }
 },
 "verdict": "PLANTED",
 "score": 14,
 "maxScore": 17,
 "headline": "13 of 13 sampled stargazers were born within 9.3 minutes of each other and starred the same 9 repos in the same order, 4 s apart.",
 "reason": null,
 "signals": [
  {
   "id": "siblings",
   "label": "Sibling crop",
   "fired": true,
   "weight": 2,
   "value": 8,
   "unit": "repos",
   "control": 0,
   "threshold": ">= 3 repos with >= 112 stars created within +-30 s, and >= 3x the same window 24 h earlier",
   "evidence": "8 other repos were created 2026-09-23 11:21:44-11:21:52Z with 222-224 stars each; the same window a day earlier has 0."
  },
  {
   "id": "ownerCohort",
   "label": "Owner birth cohort",
   "fired": true,
   "weight": 1,
   "value": 29,
   "unit": "accounts",
   "control": 2,
   "threshold": ">= 10 accounts born within +-6 min of the owner with 0 followers and >= 7 repos, and >= 3x the window 24 h earlier",
   "evidence": "29 accounts born 2026-07-21 23:53-00:05Z match the owner profile (0 followers, >= 7 repos); 2 match a day earlier."
  },
  {
   "id": "birthSpread",
   "label": "Stargazer birth spread",
   "fired": true,
   "weight": 3,
   "value": 5.9,
   "unit": "minutes (IQR)",
   "control": null,
   "threshold": "<= 60 min between the 25th and 75th percentile birth of >= 4 confirmed stargazers",
   "evidence": "The middle half of the 13 confirmed stargazers were born within 5.9 minutes, and all 13 within 9.3 minutes, on 2026-07-21 23:50-23:59Z (ids 307,793,903-307,795,340)."
  },
  {
   "id": "plantingRows",
   "label": "Planting rows",
   "fired": true,
   "weight": 3,
   "value": 1,
   "unit": "row agreement",
   "control": null,
   "threshold": ">= 0.8 of stargazer pairs star their shared repos in the same order, median gap <= 30 s",
   "evidence": "All 78 pairs of confirmed stargazers starred the shared repos in the identical order; median 4 s between stars."
  },
  {
   "id": "field",
   "label": "The field",
   "fired": true,
   "weight": 2,
   "value": 9,
   "unit": "repos",
   "control": null,
   "threshold": ">= 3 other repos starred by >= 50% of confirmed stargazers",
   "evidence": "The 13 accounts all starred the same 9 other repos; 8 are its siblings (created within 30 s of it)."
  },
  {
   "id": "hollowAccounts",
   "label": "Hollow accounts",
   "fired": true,
   "weight": 1,
   "value": 1,
   "unit": "share",
   "control": null,
   "threshold": ">= 0.75 of up to 8 checked stargazers have 0 followers and were < 180 days old when they starred",
   "evidence": "8 of 8 checked stargazers have 0 followers and were 63 days old when they starred."
  },
  {
   "id": "thinSoil",
   "label": "Thin soil",
   "fired": true,
   "weight": 1,
   "value": 56,
   "unit": "stars per KB",
   "control": null,
   "threshold": ">= 50 stars on <= 64 KB of repo and <= 10 commits",
   "evidence": "224 stars on a 4 KB repo with 4 commits."
  },
  {
   "id": "templateTwins",
   "label": "Template twins",
   "fired": true,
   "weight": 1,
   "value": 8,
   "unit": "repos",
   "control": null,
   "threshold": ">= 2 siblings share the README skeleton hash",
   "evidence": "8 of 8 checked siblings have README skeleton b9ae6852e01d, identical to this one after names and descriptions are removed."
  },
  {
   "id": "knownField",
   "label": "Known field",
   "fired": null,
   "weight": 3,
   "value": null,
   "unit": "known planters",
   "control": null,
   "threshold": ">= 3 accounts from an earlier PLANTED field starred this repo",
   "evidence": "No surveyed field in the index yet."
  }
 ],
 "siblings": {
  "from": "2026-09-23T11:21:14Z",
  "to": "2026-09-23T11:22:14Z",
  "minStars": 112,
  "controlCount": 0,
  "repos": [
   {
    "fullName": "AutocratGirder/ClashDesk",
    "createdAt": "2026-09-23T11:21:44Z",
    "offsetSeconds": 0,
    "stars": 224,
    "forks": 47,
    "ownerLogin": "AutocratGirder",
    "ownerId": 307795303,
    "ownerBornAt": "2026-07-21T23:59:38Z",
    "skeleton": "b9ae6852e01d"
   },
   {
    "fullName": "BinaryDeliverer/CodexDesk",
    "createdAt": "2026-09-23T11:21:44Z",
    "offsetSeconds": 0,
    "stars": 223,
    "forks": 48,
    "ownerLogin": "BinaryDeliverer",
    "ownerId": 307794984,
    "ownerBornAt": "2026-07-21T23:57:33Z",
    "skeleton": "b9ae6852e01d"
   },
   {
    "fullName": "AvenueSnowStep/ClaudePanel",
    "createdAt": "2026-09-23T11:21:45Z",
    "offsetSeconds": 1,
    "stars": 222,
    "forks": 48,
    "ownerLogin": "AvenueSnowStep",
    "ownerId": 307795094,
    "ownerBornAt": "2026-07-21T23:58:14Z",
    "skeleton": "b9ae6852e01d"
   },
   {
    "fullName": "BricklayerSurmount/DockForge",
    "createdAt": "2026-09-23T11:21:45Z",
    "offsetSeconds": 1,
    "stars": 223,
    "forks": 47,
    "ownerLogin": "BricklayerSurmount",
    "ownerId": 307793905,
    "ownerBornAt": "2026-07-21T23:50:36Z",
    "skeleton": "b9ae6852e01d"
   },
   {
    "fullName": "Behemothlyaoscillate/RustDeskPro",
    "createdAt": "2026-09-23T11:21:46Z",
    "offsetSeconds": 2,
    "stars": 222,
    "forks": 47,
    "ownerLogin": "Behemothlyaoscillate",
    "ownerId": 307793903,
    "ownerBornAt": "2026-07-21T23:50:36Z",
    "skeleton": "b9ae6852e01d"
   },
   {
    "fullName": "BridgeDruidCompress/TauriKit",
    "createdAt": "2026-09-23T11:21:48Z",
    "offsetSeconds": 4,
    "stars": 224,
    "forks": 47,
    "ownerLogin": "BridgeDruidCompress",
    "ownerId": 307794066,
    "ownerBornAt": "2026-07-21T23:51:50Z",
    "skeleton": "b9ae6852e01d"
   },
   {
    "fullName": "CassowaryDevelop/HelixEdit",
    "createdAt": "2026-09-23T11:21:48Z",
    "offsetSeconds": 4,
    "stars": 222,
    "forks": 47,
    "ownerLogin": "CassowaryDevelop",
    "ownerId": 307794893,
    "ownerBornAt": "2026-07-21T23:57:05Z",
    "skeleton": "b9ae6852e01d"
   },
   {
    "fullName": "centralcashierboost/ZedLite",
    "createdAt": "2026-09-23T11:21:50Z",
    "offsetSeconds": 6,
    "stars": 223,
    "forks": 47,
    "ownerLogin": "centralcashierboost",
    "ownerId": 307794291,
    "ownerBornAt": "2026-07-21T23:53:19Z",
    "skeleton": "b9ae6852e01d"
   },
   {
    "fullName": "BufferHerald/WarpLite",
    "createdAt": "2026-09-23T11:21:52Z",
    "offsetSeconds": 8,
    "stars": 224,
    "forks": 47,
    "ownerLogin": "BufferHerald",
    "ownerId": 307794603,
    "ownerBornAt": "2026-07-21T23:55:17Z",
    "skeleton": "b9ae6852e01d"
   }
  ]
 },
 "cohort": {
  "from": "2026-07-21T23:53:38Z",
  "to": "2026-07-22T00:05:38Z",
  "query": "created:2026-07-21T23:53:38Z..2026-07-22T00:05:38Z repos:>=7 followers:0",
  "count": 29,
  "controlCount": 2,
  "computed": true
 },
 "stargazers": {
  "seeds": 13,
  "confirmed": 13,
  "accounts": [
   {
    "login": "Behemothlyaoscillate",
    "id": 307793903,
    "bornAt": "2026-07-21T23:50:36Z",
    "bornExact": true,
    "via": "fork",
    "starredAt": "2026-09-23T11:49:39Z",
    "followers": 0,
    "publicRepos": 15
   },
   {
    "login": "BricklayerSurmount",
    "id": 307793905,
    "bornAt": "2026-07-21T23:50:36Z",
    "bornExact": true,
    "via": "fork",
    "starredAt": "2026-09-23T11:49:38Z",
    "followers": 0,
    "publicRepos": 15
   },
   {
    "login": "BridgeDruidCompress",
    "id": 307794066,
    "bornAt": "2026-07-21T23:51:50Z",
    "bornExact": true,
    "via": "fork",
    "starredAt": "2026-09-23T11:50:34Z",
    "followers": 0,
    "publicRepos": 16
   },
   {
    "login": "centralcashierboost",
    "id": 307794291,
    "bornAt": "2026-07-21T23:53:19Z",
    "bornExact": true,
    "via": "fork",
    "starredAt": "2026-09-23T11:50:56Z",
    "followers": 0,
    "publicRepos": 14
   },
   {
    "login": "BufferHerald",
    "id": 307794603,
    "bornAt": "2026-07-21T23:55:17Z",
    "bornExact": true,
    "via": "fork",
    "starredAt": "2026-09-23T11:49:40Z",
    "followers": 0,
    "publicRepos": 15
   },
   {
    "login": "CassowaryDevelop",
    "id": 307794893,
    "bornAt": "2026-07-21T23:57:05Z",
    "bornExact": true,
    "via": "fork",
    "starredAt": "2026-09-23T11:50:53Z",
    "followers": 0,
    "publicRepos": 16
   },
   {
    "login": "BinaryDeliverer",
    "id": 307794984,
    "bornAt": "2026-07-21T23:57:33Z",
    "bornExact": true,
    "via": "fork",
    "starredAt": "2026-09-23T11:49:36Z",
    "followers": 0,
    "publicRepos": 15
   },
   {
    "login": "AvenueSnowStep",
    "id": 307795094,
    "bornAt": "2026-07-21T23:58:14Z",
    "bornExact": true,
    "via": "fork",
    "starredAt": "2026-09-23T11:49:38Z",
    "followers": 0,
    "publicRepos": 15
   },
   {
    "login": "Lengthbriexemplify",
    "id": 307795209,
    "bornAt": "2026-07-21T23:59:00Z",
    "bornExact": false,
    "via": "cohort",
    "starredAt": "2026-09-23T11:54:11Z",
    "followers": null,
    "publicRepos": null
   },
   {
    "login": "FiscalUpgrade",
    "id": 307795234,
    "bornAt": "2026-07-21T23:59:10Z",
    "bornExact": false,
    "via": "cohort",
    "starredAt": "2026-09-23T11:52:43Z",
    "followers": null,
    "publicRepos": null
   },
   {
    "login": "ModernAnemoneStove",
    "id": 307795235,
    "bornAt": "2026-07-21T23:59:10Z",
    "bornExact": false,
    "via": "cohort",
    "starredAt": "2026-09-23T11:55:12Z",
    "followers": null,
    "publicRepos": null
   },
   {
    "login": "Emberbencontract",
    "id": 307795302,
    "bornAt": "2026-07-21T23:59:37Z",
    "bornExact": false,
    "via": "cohort",
    "starredAt": "2026-09-23T11:51:56Z",
    "followers": null,
    "publicRepos": null
   },
   {
    "login": "QuantumSkinkCry",
    "id": 307795340,
    "bornAt": "2026-07-21T23:59:52Z",
    "bornExact": false,
    "via": "cohort",
    "starredAt": "2026-09-23T11:57:18Z",
    "followers": null,
    "publicRepos": null
   }
  ],
  "birthSpreadMinutes": 5.9,
  "rowAgreement": 1,
  "medianGapSeconds": 4,
  "doors": [
   {
    "via": "fork",
    "seeds": 8,
    "confirmed": 8,
    "available": null
   },
   {
    "via": "cohort",
    "seeds": 5,
    "confirmed": 5,
    "available": null
   }
  ]
 },
 "field": {
  "id": null,
  "repos": [
   {
    "fullName": "AvenueSnowStep/ClaudePanel",
    "starredBy": 13,
    "share": 1
   },
   {
    "fullName": "Behemothlyaoscillate/RustDeskPro",
    "starredBy": 13,
    "share": 1
   },
   {
    "fullName": "BinaryDeliverer/CodexDesk",
    "starredBy": 13,
    "share": 1
   },
   {
    "fullName": "BricklayerSurmount/DockForge",
    "starredBy": 13,
    "share": 1
   },
   {
    "fullName": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "starredBy": 13,
    "share": 1
   },
   {
    "fullName": "BridgeDruidCompress/TauriKit",
    "starredBy": 13,
    "share": 1
   },
   {
    "fullName": "BufferHerald/WarpLite",
    "starredBy": 13,
    "share": 1
   },
   {
    "fullName": "CassowaryDevelop/HelixEdit",
    "starredBy": 13,
    "share": 1
   },
   {
    "fullName": "centralcashierboost/ZedLite",
    "starredBy": 13,
    "share": 1
   }
  ],
  "plantings": [
   {
    "login": "AvenueSnowStep",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:49:34Z"
   },
   {
    "login": "AvenueSnowStep",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:49:38Z"
   },
   {
    "login": "AvenueSnowStep",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:50:12Z"
   },
   {
    "login": "AvenueSnowStep",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:50:16Z"
   },
   {
    "login": "AvenueSnowStep",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:50:22Z"
   },
   {
    "login": "AvenueSnowStep",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:50:26Z"
   },
   {
    "login": "AvenueSnowStep",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:50:29Z"
   },
   {
    "login": "AvenueSnowStep",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:50:34Z"
   },
   {
    "login": "AvenueSnowStep",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:50:38Z"
   },
   {
    "login": "AvenueSnowStep",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:20:18Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:49:34Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:49:39Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:50:14Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:50:19Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:50:24Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:50:28Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:50:32Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:50:36Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:50:40Z"
   },
   {
    "login": "Behemothlyaoscillate",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:20:36Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:49:33Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:49:36Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:49:39Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:50:19Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:50:23Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:50:28Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:50:32Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:50:37Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:50:41Z"
   },
   {
    "login": "BinaryDeliverer",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:20:20Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:49:34Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:49:38Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:50:11Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:50:14Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:50:18Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:50:21Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:50:24Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:50:28Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:50:32Z"
   },
   {
    "login": "BricklayerSurmount",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:20:23Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:49:37Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:50:34Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:50:37Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:50:41Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:50:45Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:50:49Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:50:53Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:50:57Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:51:01Z"
   },
   {
    "login": "BridgeDruidCompress",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:20:22Z"
   },
   {
    "login": "BufferHerald",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:49:36Z"
   },
   {
    "login": "BufferHerald",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:49:40Z"
   },
   {
    "login": "BufferHerald",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:50:54Z"
   },
   {
    "login": "BufferHerald",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:50:58Z"
   },
   {
    "login": "BufferHerald",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:51:01Z"
   },
   {
    "login": "BufferHerald",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:51:05Z"
   },
   {
    "login": "BufferHerald",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:51:09Z"
   },
   {
    "login": "BufferHerald",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:51:14Z"
   },
   {
    "login": "BufferHerald",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:51:18Z"
   },
   {
    "login": "BufferHerald",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:20:30Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:50:49Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:50:53Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:50:57Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:51:01Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:51:06Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:51:09Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:51:13Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:51:18Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:51:22Z"
   },
   {
    "login": "CassowaryDevelop",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:20:31Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:51:52Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:51:56Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:52:00Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:52:04Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:52:08Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:52:11Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:52:16Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:52:20Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:52:24Z"
   },
   {
    "login": "Emberbencontract",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:20:53Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:52:39Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:52:43Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:52:46Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:52:51Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:52:55Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:53:01Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:53:05Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:53:09Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:53:15Z"
   },
   {
    "login": "FiscalUpgrade",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:21:18Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:54:03Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:54:11Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:54:16Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:54:20Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:54:25Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:54:31Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:54:41Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:54:48Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:54:52Z"
   },
   {
    "login": "Lengthbriexemplify",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:21:19Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:55:09Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:55:12Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:55:16Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:55:20Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:55:23Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:55:27Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:55:32Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:55:36Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:55:40Z"
   },
   {
    "login": "ModernAnemoneStove",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:21:39Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:57:04Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:57:18Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:57:27Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:57:40Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:57:48Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:57:55Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:58:07Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:58:18Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:58:32Z"
   },
   {
    "login": "QuantumSkinkCry",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:22:08Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "BinaryDeliverer/CodexDesk",
    "at": "2026-09-23T11:50:52Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "AutocratGirder/ClashDesk",
    "at": "2026-09-23T11:50:56Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "AvenueSnowStep/ClaudePanel",
    "at": "2026-09-23T11:50:59Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "BricklayerSurmount/DockForge",
    "at": "2026-09-23T11:51:02Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "Behemothlyaoscillate/RustDeskPro",
    "at": "2026-09-23T11:51:06Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "BridgeDruidCompress/TauriKit",
    "at": "2026-09-23T11:51:10Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "CassowaryDevelop/HelixEdit",
    "at": "2026-09-23T11:51:13Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "centralcashierboost/ZedLite",
    "at": "2026-09-23T11:51:17Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "BufferHerald/WarpLite",
    "at": "2026-09-23T11:51:20Z"
   },
   {
    "login": "centralcashierboost",
    "repo": "BridgeDruidCompress/Moon-FruityLoops26-FileParser",
    "at": "2026-09-24T22:20:32Z"
   }
  ]
 },
 "trace": [
  {
   "step": "repo",
   "calls": 2,
   "ms": 0
  },
  {
   "step": "siblings",
   "calls": 2,
   "ms": 0
  },
  {
   "step": "cohort",
   "calls": 2,
   "ms": 0
  },
  {
   "step": "seeds",
   "calls": 1,
   "ms": 0
  },
  {
   "step": "starred",
   "calls": 13,
   "ms": 0
  },
  {
   "step": "profiles",
   "calls": 8,
   "ms": 0
  },
  {
   "step": "soil",
   "calls": 1,
   "ms": 0
  },
  {
   "step": "twins",
   "calls": 5,
   "ms": 0
  },
  {
   "step": "score",
   "calls": 0,
   "ms": 0
  }
 ],
 "cost": {
  "githubCore": 30,
  "githubSearch": 4,
  "heliusCredits": 0
 },
 "limits": [
  "Stargazers are seen only through public doors: recent star events, fork owners, issue/PR authors, birth cohorts and sibling owners. GitHub hides the full stargazer list since 2026-06-30.",
  "Birth times are approximate: account ids are converted with the id clock (piecewise-linear anchors).",
  "A pattern, not an accusation: a repo owner can be starred by a farm without asking for it.",
  "RECORDED: this farm was surveyed 2026-09-25 12:55Z; its repos and accounts have since returned 404."
 ]
};

/** ReportSummary of the same report (the /api/fields surveyed[] and /api/recent shape). */
export const summary = {
 "fullName": "AutocratGirder/ClashDesk",
 "verdict": "PLANTED",
 "score": 14,
 "maxScore": 17,
 "stars": 224,
 "createdAt": "2026-09-23T11:21:44Z",
 "checkedAt": "2026-09-25T12:55:00Z",
 "headline": "13 of 13 sampled stargazers were born within 9.3 minutes of each other and starred the same 9 repos in the same order, 4 s apart.",
 "mint": null,
 "symbol": null,
 "fieldId": null
};

/** The id clock the library uses: the recorded global table plus this survey's exact local anchors. */
export const idclock = {
 "recordedAt": "2026-09-25T14:00Z",
 "call": "GET /user/{id} (by numeric id; ids are assigned in signup order)",
 "source": "src/anchors.js GLOBAL_ANCHORS + the local anchors of the recorded ClashDesk survey",
 "anchors": [
  {
   "id": 1000000,
   "created_at": "2011-08-23T20:40:35Z"
  },
  {
   "id": 10000002,
   "created_at": "2014-11-29T13:52:40Z"
  },
  {
   "id": 25000000,
   "created_at": "2017-01-09T05:24:12Z"
  },
  {
   "id": 50000000,
   "created_at": "2019-04-25T22:18:38Z"
  },
  {
   "id": 75000000,
   "created_at": "2020-11-25T02:36:50Z"
  },
  {
   "id": 100000000,
   "created_at": "2022-02-18T22:03:02Z"
  },
  {
   "id": 125000000,
   "created_at": "2023-02-10T07:52:45Z"
  },
  {
   "id": 150000000,
   "created_at": "2023-11-06T06:51:14Z"
  },
  {
   "id": 175000000,
   "created_at": "2024-07-08T07:42:39Z"
  },
  {
   "id": 200000001,
   "created_at": "2025-02-19T22:51:07Z"
  },
  {
   "id": 225000000,
   "created_at": "2025-08-06T12:25:07Z"
  },
  {
   "id": 250000001,
   "created_at": "2025-12-16T17:57:14Z"
  },
  {
   "id": 252500000,
   "created_at": "2026-01-01T21:29:33Z"
  },
  {
   "id": 255000000,
   "created_at": "2026-01-14T21:33:57Z"
  },
  {
   "id": 257500000,
   "created_at": "2026-01-27T09:57:08Z"
  },
  {
   "id": 260000000,
   "created_at": "2026-02-07T04:08:42Z"
  },
  {
   "id": 262500001,
   "created_at": "2026-02-19T05:03:12Z"
  },
  {
   "id": 265000000,
   "created_at": "2026-03-02T11:30:07Z"
  },
  {
   "id": 267500002,
   "created_at": "2026-03-12T02:10:26Z"
  },
  {
   "id": 270000000,
   "created_at": "2026-03-21T19:26:52Z"
  },
  {
   "id": 272500000,
   "created_at": "2026-03-31T11:05:37Z"
  },
  {
   "id": 275000000,
   "created_at": "2026-04-10T06:41:18Z"
  },
  {
   "id": 277500000,
   "created_at": "2026-04-19T15:45:07Z"
  },
  {
   "id": 280000000,
   "created_at": "2026-04-28T11:16:31Z"
  },
  {
   "id": 282500000,
   "created_at": "2026-05-07T07:39:29Z"
  },
  {
   "id": 285000000,
   "created_at": "2026-05-15T15:50:20Z"
  },
  {
   "id": 287500000,
   "created_at": "2026-05-24T17:53:33Z"
  },
  {
   "id": 290000000,
   "created_at": "2026-06-02T10:54:26Z"
  },
  {
   "id": 292500000,
   "created_at": "2026-06-10T15:27:41Z"
  },
  {
   "id": 295000000,
   "created_at": "2026-06-19T03:19:31Z"
  },
  {
   "id": 297500000,
   "created_at": "2026-06-27T21:18:33Z"
  },
  {
   "id": 300000000,
   "created_at": "2026-07-05T03:48:56Z"
  },
  {
   "id": 302500000,
   "created_at": "2026-07-11T12:40:36Z"
  },
  {
   "id": 305000002,
   "created_at": "2026-07-14T16:41:43Z"
  },
  {
   "id": 307500005,
   "created_at": "2026-07-21T09:08:04Z"
  },
  {
   "id": 310000000,
   "created_at": "2026-07-28T03:52:25Z"
  },
  {
   "id": 312500000,
   "created_at": "2026-08-03T11:52:15Z"
  },
  {
   "id": 315000000,
   "created_at": "2026-08-09T13:18:45Z"
  },
  {
   "id": 317500000,
   "created_at": "2026-08-16T06:39:02Z"
  },
  {
   "id": 320000000,
   "created_at": "2026-08-22T22:03:38Z"
  },
  {
   "id": 322500000,
   "created_at": "2026-08-29T13:24:39Z"
  },
  {
   "id": 325000000,
   "created_at": "2026-09-04T17:35:26Z"
  },
  {
   "id": 327500000,
   "created_at": "2026-09-10T12:46:58Z"
  },
  {
   "id": 330000000,
   "created_at": "2026-09-16T12:49:41Z"
  },
  {
   "id": 332500000,
   "created_at": "2026-09-22T13:08:46Z"
  }
 ],
 "local": [
  {
   "id": 307793903,
   "created_at": "2026-07-21T23:50:36Z",
   "login": "Behemothlyaoscillate"
  },
  {
   "id": 307793905,
   "created_at": "2026-07-21T23:50:36Z",
   "login": "BricklayerSurmount"
  },
  {
   "id": 307794066,
   "created_at": "2026-07-21T23:51:50Z",
   "login": "BridgeDruidCompress"
  },
  {
   "id": 307794291,
   "created_at": "2026-07-21T23:53:19Z",
   "login": "centralcashierboost"
  },
  {
   "id": 307794603,
   "created_at": "2026-07-21T23:55:17Z",
   "login": "BufferHerald"
  },
  {
   "id": 307794893,
   "created_at": "2026-07-21T23:57:05Z",
   "login": "CassowaryDevelop"
  },
  {
   "id": 307794984,
   "created_at": "2026-07-21T23:57:33Z",
   "login": "BinaryDeliverer"
  },
  {
   "id": 307795094,
   "created_at": "2026-07-21T23:58:14Z",
   "login": "AvenueSnowStep"
  },
  {
   "id": 307795303,
   "created_at": "2026-07-21T23:59:38Z",
   "login": "AutocratGirder"
  }
 ]
};

/** Where the report comes from; the site labels it with `label`. */
export const provenance = {
 "fixture": "test/fixtures/raw.planted.clashdesk.json",
 "recordedAt": "2026-09-25T12:49Z..12:58Z",
 "generatedBy": "node test/record.mjs --offline",
 "label": "RECORDED",
 "note": "Rebuilt by test/record.mjs from research/samples (report.example.planted.json, fields.example.json, readme-skeletons.json), all recorded on mainnet GitHub 2026-09-25 12:49-12:58Z. Starred lists hold only the stars on the target and its field (the other stars were not recorded). READMEs are stored as recorded skeleton hashes. The repos and accounts returned 404 by ~15:40Z the same day."
};

export default report;
