// Records fixtures and regenerates lib/reference-report.mjs. Run from app/:
//   node test/record.mjs --offline                                  (only lib/reference-report.mjs, from the committed farm fixture)
//   GITHUB_TOKEN=... node test/record.mjs                           (also the live fixtures; HELIUS_API_KEY from app/.env or the shell)
//   GITHUB_TOKEN=... node test/record.mjs --only tinygrad           (re-record only fixtures whose file name matches)
//   ... --grown <owner/repo>   the young organic repo for raw.grown.riso-windowseat.json (skipped without it: the
//                              recorded one is an individual's repo, so its name is not kept in this repo)
//
// Reads / writes (paths from the repo root):
//   test/fixtures/raw.planted.clashdesk.json    READ ONLY. The recorded star farm AutocratGirder/ClashDesk, surveyed on mainnet
//                                               GitHub 2026-09-25 12:49-12:58Z. Its repos and accounts returned 404 by ~15:40Z the
//                                               same day, so it can never be re-recorded; the committed file is the recording.
//                                               A pattern, not an accusation.
//   test/fixtures/raw.grown.riso-windowseat.json   live collect() on a young organic repo (--grown)
//   test/fixtures/raw.seedling.bmc.json            live collect() on the BMC pump.fun mint (its repo has 3 stars)
//   test/fixtures/raw.grown.tinygrad.json          live collect() on tinygrad/tinygrad (33k stars, 5 years old: the star-event door)
//   Live fixtures are passed through anonymize() before they are written: every login becomes sample-user-NN /
//   sample-owner-NN (the organization tinygrad is kept), ids, dates and counts stay, READMEs keep their skeleton.
//   app/lib/reference-report.mjs                   analyze(ClashDesk raw), served by /api/fields as `featured` until the store
//                                                  holds a live PLANTED report, plus the named exports the site generates
//                                                  site/src/data from (node site/tools/featured.mjs)
import fs from 'node:fs/promises';
import * as fsSync from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { collect, analyze, summarize, anonymize, GLOBAL_ANCHORS } from '../../src/index.js';

const app = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fx = path.resolve(app, '../test/fixtures');

// Load app/.env (if any) without printing it; the shell wins.
try {
  for (const line of fsSync.readFileSync(path.join(app, '.env'), 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
  }
} catch {}

// ---------- 1) the recorded farm -> lib/reference-report.mjs
const planted = JSON.parse(await fs.readFile(path.join(fx, 'raw.planted.clashdesk.json'), 'utf8'));
const ref = analyze(planted);
// Local anchors of this survey (the owner and every fetched profile): exact GitHub signup times, used by the id clock.
const localAnchors = [
  { id: planted.owner.id, created_at: planted.owner.createdAt, login: planted.owner.login },
  ...Object.entries(planted.profiles).map(([login, p]) => ({ id: p.id, created_at: p.createdAt, login })),
].sort((a, b) => a.id - b.id);
const idclock = {
  recordedAt: '2026-09-25T14:00Z',
  call: 'GET /user/{id} (by numeric id; ids are assigned in signup order)',
  source: 'src/anchors.js GLOBAL_ANCHORS + the local anchors of the recorded ClashDesk survey',
  anchors: GLOBAL_ANCHORS.map((a) => ({ id: a.id, created_at: a.createdAt })),
  local: localAnchors,
};
const provenance = {
  fixture: 'test/fixtures/raw.planted.clashdesk.json',
  recordedAt: '2026-09-25T12:49Z..12:58Z',
  generatedBy: 'node test/record.mjs --offline',
  label: 'RECORDED',
  note: planted._note,
};
await fs.writeFile(path.join(app, 'lib/reference-report.mjs'),
  `// GENERATED by app/test/record.mjs: analyze() on the recorded ClashDesk survey (test/fixtures/raw.planted.clashdesk.json).\n` +
  `// Do not edit by hand; re-run \`node test/record.mjs --offline\` (in app/) after any change to src/analyze.js.\n` +
  `// default / report: the CropReport, served by /api/fields as \`featured\` (source: 'fixture') until the store holds a live PLANTED report.\n` +
  `// The site generates site/src/data from these exports (featured.json = report, idclock.json = idclock).\n` +
  `export const report = ${JSON.stringify(ref, null, 1)};\n\n` +
  `/** ReportSummary of the same report (the /api/fields surveyed[] and /api/recent shape). */\n` +
  `export const summary = ${JSON.stringify(summarize(ref), null, 1)};\n\n` +
  `/** The id clock the library uses: the recorded global table plus this survey's exact local anchors. */\n` +
  `export const idclock = ${JSON.stringify(idclock, null, 1)};\n\n` +
  `/** Where the report comes from; the site labels it with \`label\`. */\n` +
  `export const provenance = ${JSON.stringify(provenance, null, 1)};\n\n` +
  `export default report;\n`);
console.log(`clashdesk (recorded) -> ${ref.verdict} ${ref.score}/17: ${ref.headline}`);

// ---------- 2) live fixtures
if (!process.argv.includes('--offline')) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) { console.error('set GITHUB_TOKEN (e.g. GITHUB_TOKEN=$(gh auth token) node test/record.mjs) or pass --offline'); process.exit(1); }
  const rpcUrl = process.env.HELIUS_API_KEY ? `https://mainnet.helius-rpc.com/?api-key=${process.env.HELIUS_API_KEY}` : undefined;
  const only = process.argv.includes('--only') ? process.argv[process.argv.indexOf('--only') + 1] : null;
  const grown = process.argv.includes('--grown') ? process.argv[process.argv.indexOf('--grown') + 1] : null;
  const names = new Map(); // login -> placeholder for this run; holds real logins, never written
  for (const [file, q] of [
    ['raw.grown.riso-windowseat.json', grown],
    ['raw.seedling.bmc.json', '64S9QFTFhrcLWsXWjTBkaWPS4asdcrQGwvVQWxUjpump'],
    ['raw.grown.tinygrad.json', 'tinygrad/tinygrad'],
  ]) {
    if ((only && !file.includes(only)) || !q) continue;
    const raw = anonymize(await collect(q, { token, rpcUrl, budgetMs: 30000 }), { keep: ['tinygrad'], map: names });
    raw._note = `Recorded live by test/record.mjs at ${raw.checkedAt}. GitHub logins replaced by anonymize() placeholders at record time.`;
    await fs.writeFile(path.join(fx, file), JSON.stringify(raw, null, 1));
    const r = analyze(raw);
    console.log(`${file} -> ${r.verdict} ${r.score}/17 (${raw.cost.githubCore} core, ${raw.cost.githubSearch} search, ${raw.elapsedMs} ms): ${r.headline}`);
  }
}
